# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-01 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
